### ISSUE TITLE
Issue with Unicode characters

### ISSUE THREAD

**Issue by moogle19** [twking7/fixed_width#1]
Hi,
I am not sure if this is the expected behaviour or not, but currently if I try to read a line with an umlaut (äüö..) the fixed_width parsing fails.
This is because the width is defined in bytes and not characters. My expectation was, that the StringReader interprets the width as (unicode) character count.

**Comment by twking7** [comment]
Hey, sorry I didn't get to this sooner, for some reason GitHub didn't notify me.

It is intended that the width of the file is in bytes, _not_ characters. I can make this more clear in the README. That said, when using the StringReader, you should be able to parse unicode content so long as it fits in your width.
