### ISSUE TITLE
Allow a field to be ignored.

### ISSUE THREAD

**Issue by frgomes** [twking7/fixed_width#10]
## Motivation

I'm processing 40 years of data, millions if not billions of records, from a time when UTF8 didn't even exist. Also, there were bugs in past, which saved binary data onto fields which should be text. I would like to fix or circumvent these difficulties. I have three options:

1. Cleanse the data in the file system before ingestion. This is problematic, because the files involved are relatively big and I don't see the point of creating more big files just because a relatively small number of records need to be fixed.
2. Cleanse the data as a stream during ingestion. In Java this would be relatively simple to be done, but in Rust it is far from simple, involving a lot of async programming which looks "too much" to me, a lot of complexity and over engineering inside just a little of simple code which does the job which really matters.
3. Cleanse the data on-the-fly, during ingestion, performing some sort of custom logic.

NOTE: crate fixed_width assumes that text data is encoded as UTF8, which is not true in this case, which begs the question: Shouldn't we just pass the encoding to fixed_width, so that it know that a particular encoding should be employed instead of UTF8? The answer is yes. However, even if I had a chance to pass the encoding I need to fixed_width, this would be insufficient for fixing dirty characters still present in the data.

## Overview

I would like to employ package fixed_width as usual, except that some fields I would like to be ignored by fixed_width. This way, I can obtain the data myself, perform whatever tricks I need to do to fix the data, and finally assign the resulting data myself onto the record which holds the ingested data.

## About this ticket

I would like to simply comment out fixed_width annotations on problematic fields, but this expedient does not work, since fixed_width requires that all fields of an annotated struct contain field descriptions. This would be the preferred alternative: simply comment out the annotation on problematic fields.

Alternatively, we could "invent" another tag which tells fixed_width to ignore a certain field later when the data is processed, something like: ``ignore = "true"`` like shown below:

```
...
    #[fixed_width(range = "49..52", ignore = "true")]
    pub days: u16,
...
```

**Comment by frgomes** [comment]
@twking7 : Could you please assign this ticket to me?
Your feedback is welcome.
Thanks

**Comment by twking7** [comment]
Hello @frgomes , thanks for reaching out. Quick question, did you try using the built in ignore in serde? https://serde.rs/field-attrs.html#skip_deserializing

While I don't recall anyone implementing something specific for this field, it may do what you want.

Alternatively, can you deserialize to a `Vec<u8>`? This would read the bytes but not try to interpret them as UTF8.

**Comment by frgomes** [comment]
@twking7 Indeed! Serde provides the functionality I need. No need to implement anything:

```
    #[fixed_width(range = "49..52")]
    #[serde(skip)]
    pub days: u16,

```

Thanks a lot!

**Comment by twking7** [comment]
Glad that helped! Do let me know if there any issues with that, as it's
supposed to work and if not is a potential bug.
