### ISSUE TITLE
Please update syn crate

### ISSUE THREAD

**Issue by frosch01** [twking7/fixed_width#11]
Hi,

I would appreciate to use the repo for my work. However, the fixed_width_derive uses the outdated version 1 of syn crate? It would be really helpful to update to the latest version. 

Any maintainers still working on it?

Thx

Ralph

**Comment by twking7** [comment]
Hello, I can probably do this within the next week or if you're willing to
take it on I can approve.

**Comment by frosch01** [comment]
I really would love to contribute. But I feel not comfortable in writing macros in Rust. I tried to map with some suggestions on discussion at stackoverflow, however it seems most of the code needs to be adapted as API changed a lot from sync 1.0 to sync 2.0. If you are familiar with sync 2.0, perhaps it would be better if you take the job.

Let me know if you do not find the time. I will then give it a try, again.

**Comment by twking7** [comment]
If you'd like to take a try by all means do so, it would be greatly
appreciated. I admit I do not have experience with syn 2.0, was banking on
being able to figure it out.

**Comment by frosch01** [comment]
Rust macros cool as long as do not need to implement them...

**Comment by twking7** [comment]
Hey, this managed to be simpler than anticipated, got a PR up here: https://github.com/twking7/fixed_width/pull/12

Going to do a little more testing but should be able to merge this soon.

**Comment by twking7** [comment]
@frosch01 Ok, pushed a new version 0.6.0 that uses syn 2.0. Let me know if you have any issues.
