### ISSUE TITLE
Unexpected value when deserializing into array of optional elements

### ISSUE THREAD

**Issue by ongchi** [twking7/fixed_width#7]
When deserializing into an array with Option type with multiple elements, including tuples or multi-field structs. If `None` value visited, the deserialized result will skip extra fields.

For example:

```rust
let s = " 222 111         253 254 121 232";
let mut fields = vec![];
for i in 0..8 {
    fields.push(Field::default().range(i * 4..i * 4 + 4))
}

let arr: [Option<(u8, u8)>; 4] = fixed_width::from_str_with_fields(s, fields.clone()).unwrap();
for p in arr.iter() {
    println!("{:?}", p);
}
```

expected:

```rust
Some((222, 111))
None
Some((253, 254))
Some((121, 232))
```

got:

```rust
Some((222, 111))
None
None
Some((253, 254))
```

BTW, elements with single field will just works as expected.

```rust
let arr: [Option<u8>; 8] = fixed_width::from_str_with_fields(s, fields.clone()).unwrap();
for p in arr.iter() {
    println!("{:?}", p);
}
```

got:

```rust
Some(222)
Some(111)
None
None
Some(253)
Some(254)
Some(121)
Some(232)
```

**Comment by twking7** [comment]
Interesting, thanks for the report. I will take a look this weekend.

**Comment by twking7** [comment]
OK, so I looked into this and here's what seems to be happening. Apologies if you've already figured this out, I'm also typing this out for context.

You've defined 8 fields, but every 2 consecutive fields are sort of part of the same entity - the `Option<(u8, u8)>`. So when we hit a value that the deserializer will interpret as `None` (in this case, an empty string), then it skips the field - but since each field is 4 bytes, it only skips 4 bytes, then continues deserializing at the next 4, which is also empty so you get another `None`.

I'm not sure if there's a great way around this aside from implementing a custom `SeqAccess` for tuples that expect each tuple member to be a separate field. I'll give it some thought how that may work, but if you already have some ideas here please do share!

One way to work around this could be to define the tuple members as optional like so:

```rust
let arr: [(Option<u8>, Option<u8>); 4] = fixed_width::from_str_with_fields(s, fields.clone()).unwrap();
```

**Comment by ongchi** [comment]
I'm new to serde and still figuring out how it works, please correct me if I get wrong.

Fixed width format is more like a sequence, in most situations, we've got the range of fields to determine each item in this sequence, but unlike other format, says JSON, would easily determine where the start/end of the nested sequence by brackets. So, it's impossible to tell how the sequence start or end when deserializing unless introduced some marks, or even nested fields, then in the method `deserialize_any` could forward field data to proper method (pass 8 bytes instead 4 for the example).

**Comment by twking7** [comment]
Right, and the additional issue raised by the `Option` is that we cannot inspect the inner type to determine if it is a tuple/array and its length, so we cannot consume the correct number of fields.

**Comment by ongchi** [comment]
I'm working on redesign the `Field` to make `FixedWidth` works with nested structure better. Something like:

```rust
pub enum FieldSet {
    /// For single Field
    Field(Field),
    /// For Sequence of Fields
    FieldSeq(Vec<FieldSet>),
}
```

And one could implement `FixedWidth` trait for a struct like:

```rust
#[derive(Deserialize)]
struct Test {
    a: i32,
    b: i32,
    c: Vec<i32>,
    d: i32,
}

impl FixedWidth for Test {
    fn fields() -> Vec<FieldSet> {
        fieldset![
            field!(0..2),
            field!(2..4),
            fieldset![
                field!(4..6),
                field!(6..8),
            ],
            field!(0..10)
        ]
    }
} 
```

Or, with procedural macro like this:

```rust
#[derive(FixedWidth, Deserialize)]
struct Test {
    #[fixed_width(range=0..2)]
    a: i32,
    #[fixed_width(range=2..4)]
    b: i32,
    #[fixed_width(range_set=[4..6, 6..8])]
    c: Vec<i32>,
    #[fixed_width(range=8..10)]
    d: i32,
}
```

For sure this will introduce some breaking changes, but make `FixedWidth` more capable when handling with `Vec<T>`.

Any comments?

**Comment by twking7** [comment]
I think that looks interesting, and I'm looking forward to seeing what you come up with. Let me know if you have any questions or would like some reviews!

**Comment by ongchi** [comment]
The new implementation is WIP but is functional and should pass all tests currently. The next step is to update derived macros to work with this implementation. I'm going to spend some time to get this done, maybe in few days.
